apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-config
  namespace: fraud-detection
data:
  application-prod.yml: |
    server:
      port: 8080
      servlet:
        context-path: /fraud-detection

    spring:
      application:
        name: fraud-detection-service
      
      # PostgreSQL数据库配置
      datasource:
        url: jdbc:postgresql://postgres-service:5432/frauddb
        driver-class-name: org.postgresql.Driver
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        hikari:
          maximum-pool-size: 20
          minimum-idle: 5
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
      
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
              batch_size: 20
            order_inserts: true
            order_updates: true
      
      # Kafka集群配置
      kafka:
        bootstrap-servers: ${KAFKA_BROKERS}
        consumer:
          group-id: fraud-detection-group
          auto-offset-reset: earliest
          enable-auto-commit: false
          max-poll-records: 500
          session-timeout-ms: 30000
          heartbeat-interval-ms: 10000
        producer:
          batch-size: 16384
          buffer-memory: 33554432
          compression-type: gzip
          retries: 3
          acks: all

    # 管理端点配置
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
      prometheus:
        metrics:
          export:
            enabled: true

    # 欺诈检测配置
    fraud:
      detection:
        amount:
          threshold: 10000
        transaction:
          count:
            threshold: 5
        time:
          window:
            minutes: 60
        amount:
          sum:
            threshold: 50000
      alert:
        enabled: true

    # 日志配置
    logging:
      level:
        com.faud.frauddetection: INFO
        org.hibernate.SQL: WARN
        org.springframework.kafka: WARN
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 